Click "PMTQ"
(*Click "PMT-D"*)
(*Click "PMT-Prod"*)

waitfor 10, "PMTLogin"

Click "PMTLogin"
TypeText mondij
Click "PMTPassword"
TypeText Playerb8
Click "LoginButton"
wait 5

Click "ProtoButton"
(*Click "CreateNewPlayer"*)
Click "NewPlayer"
wait 5

Click "PlayerNameField"
TypeText AutoTestSprint58_143_18_Contexts

Click "PlayerURIField"
TypeText "mgid:file:AutoTestSprint57_142Contexts:mtvnservices.com:"

Click "SiteSupportEmail"
TypeText "john.mondi@mtvn.com"

Click "GroupDDM"
Click "protodd"

Click "EnabledButton"

(*Click "ExternalConfigButton"
MoveTo "ExternalConfigList"*)
wait 5

Click "CreateButton"

wait 2

Click "OkButton"
wait 5

Click "CreatedButton"
wait 3

Click "CreatedButton"

Click "CheckStatus"
wait 5
(*Click "EditPlayer"*)
Click "PlayerEdit"

Click "BaseSettings"
Moveto "AlternativeDevices"
Moveto "AlternativeDevicesDisabled"
Click "AlternativeDevicesDisabled"
Click "AlternativeDevicesEnabled"

Click "HTML5_SSID"
TypeText "SSID_BaseSettings"


Click "HTML5MediagenField"
typeText commandKey, "a"
typetext backspace
TypeText "http://media.mtvnservices.com/mediagen.php"

(*drag "DownSlider"
drop "DownArrow"*)


click "PlayerSettings"

click "AddContext"
click "Context2"
doubleclick "Context2title"
typeText commandKey, "a"
typetext backspace
typeText "AddURIContext"

click "ContextType"
click "ContentID"
click "AddURIField"
typetext "AddURITest01"

click "AddURIButton"

click "AddURI02"
typetext "AddURITest02"

click "AddURIButton"

click "AddURI02"
typetext "AddURITest03"

click "AddSettings"
click "Advertising"
click "AddButton"
(*moveto "AddSettingsDefault"*)

Click "DoubleClick"
Click "FreeWheel"

click "HTML5_SSID_Field"
typeText "HTML5SSIDURIContext"


wait 5
click "PlayerSettings"

click "addContext"

click "Context3"
doubleclick "Contexttitle"
typeText commandKey, "a"
typetext backspace
typeText "HTML5Version"
click "ContextType"
click "Device"
click "DeviceField"
typetext "iPad"


click "AddSettings"

drag "AddSettingsSlider"
drop "AddSettingsSlider03"

moveto "AlternativeDevicesSetting"
click "AlternativeDevicesSetting"
click "HTML5PlayerVersion"
click "AddButton"

(*moveto "PlayerSetupVersion"
click "PlayerSetupVersion"*)

click "HTML5PlayerVersionDDM"
(*click "Player1.0.0"*)
click "Player1.1.2"


(*click "AddButton"*)

(*
moveto "Enabled"
click "Enabled"
click "Disabled"
*)

click "AddSettings"
click "Advertising"
moveto "HTML5_SSID_Context"

click "addButton"

click "HTML5_SSID_Field"
typeText "HTML5_SSID_Test"


Click "DoubleClick"
Click "FreeWheel"

click "Publishbutton"
