(*Click "PMT-Prod"*)

(*Click "PMT-D"*)

Click "PMTQ"

waitfor 10, "PMTLogin"

Click "PMTLogin"
TypeText mondij
Click "PMTPassword"
TypeText playerBB77
Click "LoginButton"
wait 5

Click "ProtoButton"
Click "CreateNewPlayer"


Click "NewPlayer"
wait 5

Click "PlayerNameField"
TypeText AutoTest180
Click "PlayerURIField"
TypeText "mgid:file:AutoTest180:mtvnservices.com:"

Click "SiteSupportEmail"
TypeText "john.mondi@mtvn.com"

Click "GroupDDM"
Click "protodd"

Click "EnabledButton"

(*Click "ExternalConfigButton"
MoveTo "ExternalConfigList"*)
wait 5

Click "CreateButton"

wait 2

Click "OkButton"

wait 5

Click "LastEdited"
wait 2
Click "LastEdited"

Click "CheckStatus"
wait 5
(*Click "EditPlayer"*)
Click "PlayerEdit"

Click "BaseSettings"

Moveto "AlternativeDevices"
Moveto "AlternativeDevicesDisabled"
Click "AlternativeDevicesDisabled"
Click "AlternativeDevicesEnabled"

Click "HTML5_SSID"
TypeText "SSID_BaseSettings"

Click "HTML5MediagenField"
typeText commandKey, "a"
typetext backspace
TypeText "http://media.mtvnservices.com/mediagen.php"

drag "BaseLevelSlider"
drop "BaseLevel3"

Moveto "MediaGenSecurity"
Click "UseMRSSmediagen03"
Click "MRSSmediagenDDM"
Click "MRSSmediagenEnabled"

click "PlayerSettings"
click "AddSettings"
drag "AddSettingsSlider"
drop "AddSettingsSlider03"
Click "UseMRSSmediagen03"
click "AddButton"

click "AddSettings"
click "Advertising"
click "AddButton"

click "DoubleClick"
click "FreeWheel"

(*moveto "FreeWheelDefault"*)
moveto "FWDefaultExpression"
(*click "FWDDM"*)
click "FWtimeBtwnAds"
typetext backspace
typetext "60000"


click "HTML5SSID"
typetext "12345"

click "AddContext"
click "Context2"
click "Context2title"
typeText commandKey, "a"
typetext backspace
typeText "HTML5Enabled"
click "ContextType"
click "UserAgentDD"
click "DeviceField"
typetext "iPad"

click "AddSettings"
drag "AddSettingsSlider"
drop "AddSettingsSlider03"

(*moveto "AlternativeDevicesSetting"
click "AlternativeDevicesSetting"*)
click "HTML5PlayerVersion"
click "AddButton"

click "AddSettings"
drag "AddSettingsSlider"
drop "AddSettingsSlider02"

click "ConvivaReportingSetting"
click "AddButton"

click "AddSettings"
drag "AddSettingsSlider"
drop "AddSettingsSlider05"

(*click "FormFactor"*)
click "FormFactorOverride"
click "guiPadding"
click "AddButton"

(*click "FormFactorDDM"*)

Click "FormFactorOverrideField"
TypeText "1:2.+3:4.-5:6.-7:*"

moveTo "guiPaddingDDM"
click "ContentSettings_TopLeft"
typeText "1"
click "ContentSettings_TopRight"
typeText "2"


click "PlayerSettings"
click "AddContext"
click "Context3"
click "Context3title"
typeText commandKey, "a"
typetext backspace
typeText "CA"

click "ContextType"
click "GEO"
click "GEO_RegexField"
typeText "(CA)"

click "AddSettings"
drag "AddSettingsSlider"
drop "AddSettingsSlider03"

click "PlayerFeed"
click "AddButton"

click "CustomErrorSlateField"
typeText "http://www.crwflags.com/fotw/images/c/ca.gif"

click "Network"
(*click "PlayerSettings"*)
click "AddSettings"

drag "AddSettingsSlider"
drop "AddSettingsSlider04"
click "ShareSettings"
click "UserClipping"
click "UserClippingContinueWatching"
click "AddButton"

moveto "ContinueWatchingDDM"
moveto "InPlayer"

click "ContinueWatchingDDM"
click "LinkToSite"

moveto "UserClippingDDM"
moveto "ShareSettingsDDM"

click "BaseSettings"

click "BaseViralPlayerNameField"
typetext "BaseViralPlayerName"

click "BaseNetworkPlayerNameField"
typetext "NetworkPlayerName"

click "BasePartnerPlayerNameField"
typetext "BasePartnerPlayerName"

click "BaseOmnitureMediaTrackingDDM"
click "BaseOmnitureMediaTrackingEnabled"

moveto "BaseOmnitureHeartbeatsEnabledDefault"

(*click "BaseOmnitureHeartbeatsDDM"
click "BaseOmnitureHeartbeatsEnabled"*)

(*click "BaseOmnitureMediaLiveEventDDM"
click "BaseOmnitureMediaLiveEventEnabled"*)

(*
click "BaseOmnitureLiveEventIDs"
typeText "LIVE123456"

drag "BaseSettingSlider"
drop "BaseSettingSlider02"

click "BaseOmnitureAdTrackingDDM"
click "BaseOmnitureAdTrackingEnabled"

click "BaseTrackingServerField"
typeText "BaseTrackingServer"

click "BaseNetworkSuiteNameField"
typeText "BaseNetworkSuiteName"

click "BasePartnerSuiteNameField"
typeText "BasePartnerSuiteName"

click "BaseViralSuiteNameField"
typeText "BaseViralSuiteName"

click "BaseVisitorNameSpaceDDM"
click "BaseVisitorNameSpaceEnabled"
*)

click "PublishButton"

click "FormFactorOverrideOK"

if ImageFound("OKBUtton")
	Click FoundImageLocation()
end if


wait 5


click "Players"
wait 4

Click "LastEdited"
wait 2
Click "LastEdited"

Click "CheckStatus"
wait 5
(*Click "EditPlayer"*)
Click "PlayerEdit"

click "BaseSettings"

doubleClick "BaseSettingPlayerNameField"
typetext backspace
TypeText AutoTest175CheckModified
Click "PublishButton"

wait 5


click "Players"

Click "LastEdited"
wait 2
Click "LastEdited"

Click "CheckStatus"
wait 5
(*Click "EditPlayer"*)
Click "PlayerEdit"

click "BaseSettings"
moveto "ModifiedField"





(*
click "AddSettings"
drag "AddSettingsSlider"
drop "AddSettingsSlider2"

click "ReportingSetting"

click "AddButton"

click "OmniturePropertyOverridesField"
typeText "OmniturePropertyOverrides"

click "CustomField"
TypeText "CustomField"

drag "ContextSlider"
drop "ContextSlider03"

click "CharacterSetField"
TypeText "12345"

click "DataCenter"
TypeText "6789"

click "DevTestSuiteName"
typeText "DevTestSuite"

click "VisitorNameSpaceDDM"
click "VisitorNameSpaceEnabled"

click "OmnitureAdTrackingDisabled"
click "OmnitureAdTrackingEnabled"
click "TrackingServerField"
typeText "trackingServer.mtv.com"

click "ViralSuiteNameField"
typeText "ContextViralSuiteName"

click "PartnerSuiteNameField"
typeText "ContextPartnerSuiteName"

click "NetworkSuiteNameField"
typeText "ContextNetworkSuiteName"
*)

(*drag "OmniSlider"
drop "OmniSlider2"*)


(*
click "ViralPlayerNameField"
typeText "ViralPlayerName"

click "PartnerPlayerNameField"
typeText "PartnerPlayerName"

click "NetworkPlayerNameField"
typeText "NetworkPlayerName"

click "OmnitureMediaTrackingDDM"
click "OmnitureMediaTrackingEnabled"

click "OmnitureMediaLiveEventDDM"
click "OmnitureMediaLiveEventEnabled"

click "BaseOmnitureLiveEventIDs"
typeText "LIVE123456Context"
*)

(*click "OmniturePropertyOverridesField"
typeText "OmniturePropertyOverrides"*)

(*add values*)

click "PublishButton"
