(*Click "PMTQ"*)
Click "PMT-D"
(*Click "PMT-Prod"*)

waitfor 10, "PMTLogin"

Click "PMTLogin"
TypeText mondij
Click "PMTPassword"
TypeText playerB88
Click "LoginButton"
wait 5

Click "ProtoButton"
Click "CreateNewPlayer"


Click "NewPlayer"
wait 5

Click "PlayerNameField"
TypeText AutoTestPublishMessage

Click "PlayerURIField"
TypeText "mgid:file:AutoTestPublishMessage:mtvnservices.com:"

Click "SiteSupportEmail"
TypeText "john.mondi@mtvn.com"

Click "GroupDDM"
Click "protodd"

Click "EnabledButton"

(*Click "ExternalConfigButton"
MoveTo "ExternalConfigList"*)
wait 5

Click "CreateButton"

wait 2

Click "OkButton"

wait 5

Click "LastEdited"
wait 2
Click "LastEdited"

Click "CheckStatus"
wait 5
(*Click "EditPlayer"*)
Click "PlayerEdit"

(*Click "BaseSettings"

Moveto "AlternativeDevices"
Moveto "AlternativeDevicesDisabled"
Click "AlternativeDevicesDisabled"
Click "AlternativeDevicesEnabled"

Click "HTML5_SSID"
TypeText "SSID_BaseSettings"

Click "HTML5MediagenField"
typeText commandKey, "a"
typetext backspace
TypeText "http://media.mtvnservices.com/mediagen.php"*)

click "PlayerSettings"
click "AddSettings"
click "Advertising"
click "AddButton"

click "DoubleClick"
click "FreeWheel"

moveto "FreeWheelDefault"
moveto "FWDefaultExpression"




click "AddContext"
click "Context2"
doubleclick "Context2title"
typeText commandKey, "a"
typetext backspace
typeText "HTML5Enabled"
click "ContextType"
click "UserAgentDD"
click "DeviceField"
typetext "/iPad/i"


click "AddSettings"
drag "AddSettingsSlider"
drop "AddSettingsSlider2"

click "ReportingSetting"

click "AddButton"

click "OmniturePropertyOverridesField"
typeText "OmniturePropertyOverrides"

click "CustomField"
TypeText "CustomField"

drag "ContextSlider"
drop "ContextSlider03"

click "CharacterSetField"
TypeText "12345"

click "DataCenter"
TypeText "6789"

click "DevTestSuiteName"
typeText "DevTestSuite"

click "VisitorNameSpaceDDM"
click "VisitorNameSpaceEnabled"

click "OmnitureAdTrackingDisabled"
click "OmnitureAdTrackingEnabled"
click "TrackingServerField"
typeText "trackingServer.mtv.com"

click "ViralSuiteNameField"
typeText "ContextViralSuiteName"

click "PartnerSuiteNameField"
typeText "ContextPartnerSuiteName"

click "NetworkSuiteNameField"
typeText "ContextNetworkSuiteName"

(*drag "OmniSlider"
drop "OmniSlider2"*)


click "ViralPlayerNameField"
typeText "ViralPlayerName"

click "PartnerPlayerNameField"
typeText "PartnerPlayerName"

click "NetworkPlayerNameField"
typeText "NetworkPlayerName"

click "OmnitureMediaTrackingDDM"
click "OmnitureMediaTrackingEnabled"

click "OmnitureMediaLiveEventDDM"
click "OmnitureMediaLiveEventEnabled"

click "BaseOmnitureLiveEventIDs"
typeText "LIVE123456Context"

(*click "OmniturePropertyOverridesField"
typeText "OmniturePropertyOverrides"*)

(*add values*)

click "PublishButton"





















